### ISSUE TITLE
Add generic typing for endpoints body

### ISSUE THREAD

**Issue by Sc0ra** [makenotion/notion-sdk-js#111]
Since I started using Notion API and this SDK, I wanted to work around typing.
Because the notion API format is quite heavy, it's easy to do mistakes when filling properties, at page update for example.

I opened a pull request #103 last week on this repository to show an example of what could be done to enable body validation by typescript during development.
This PoC shows how we could use generic typing to validate the page update method inputs based on the page definition.

Would be glad if you can give me some feedbacks !

**Comment by EnixCoda** [comment]
Having some similar issues too. I'm using this package with strict TypeScript checks.

Some typings on the request APIs should be updated include only part of them, e.g. `notion.blocks.children.append` should not mark `id`, `created_time`, `last_edited_time`, `has_children` as required properties on `children` because those are created at server side.

Some typings do not match the verification logic. For example, when creating page with `notion.pages.create`, to set the page title, in the `properties`, `title: { type: 'title', text: { ... } }` would pass TS check but throws error at runtime validation instructing me to update it to such undocumented structure: 
```
title: {
  type: [
    {
      type: "text",
      text: { content: "Test Title" },
    },
  ],
}
```

Although it runs without throwing runtime errors, the title is not properly set.

---

I've not looked into the implementation details of this SDK, but logging the issues here first. Will see what I can do later.

**Comment by Sc0ra** [comment]
Hello @blackmad @aoberoi

Before I invest some time in doing the same work for every method, I would really like to have your feedback on what I did with this PR.
Don't hesitate to tell me if you want more details around this.

**Comment by blackmad** [comment]
@pllnk is Notion's resident type wizard and will be thinking about the future architecture of the client library, I'll let him chime in here!

**Comment by rhart92** [comment]
As the types are now being auto-generated, I'm going to close this issue. Hopefully the generated types are more complete 🙏
