### ISSUE TITLE
How to add property to database

### ISSUE THREAD

**Issue by adelin-b** [makenotion/notion-sdk-js#123]
I have  a database with a select property that I need to dynamically generate. How can I do that ? It seems that I cannot edit database properties using `notion.pages.update` as it return me an error saying `cannot find object` even if I was actually able to retrieve the database with this id just before.

**Comment by alicial** [comment]
I think you might be trying to add a new select option, which we started supporting: https://developers.notion.com/changelog/select-values-can-now-be-dynamically-created-via-create-and-update-page-endpoints-other-updates-since-public-beta-launch

If you're still having this issue, please contact us at developers@makenotion.com
