### ISSUE TITLE
[Block] BulletedListItemBlock children is undefined when has_children is true

### ISSUE THREAD

**Issue by nartc** [makenotion/notion-sdk-js#147]
Report bugs here only for the Node JavaScript library.

If you're having problems using Notion's API, or have any other feedback about the API including feature requests for the JavaScript library, please email support at developers@notion.com.

**Describe the bug**
When a `BulletedListItemBlock` has nested children, the `children` is undefined

![image](https://user-images.githubusercontent.com/25516557/125172770-18522700-e181-11eb-93b1-42efc6160603.png)
![image](https://user-images.githubusercontent.com/25516557/125172771-18eabd80-e181-11eb-8901-ed76124e3db5.png)
![image](https://user-images.githubusercontent.com/25516557/125172781-23a55280-e181-11eb-9895-ef4f7d9a573f.png)

**To Reproduce**
Node version: 14.x
Notion JS library version: 0.2.1

**Expected behavior**
`bulleted_list_item.children` should have data when `bulleted_list_item.has_children` is true

**Comment by pascalporedda** [comment]
I'm experiencing the same type of issue, but apparently this does happen with all the nested structures (TODOs, bulletlist, numbered and toggle list).

**Comment by cwang314** [comment]
Hi @nartc, thanks for the report and sorry for the delayed response. Because Notion's document structure is an unboundedly wide and deep tree of blocks, we wanted to design the endpoints in a way that only steps in one direction at a time. That is to say: if you want to get all the direct children of a block, you use the paginated `GET /v1/blocks/:id/children` endpoint. In order to go down a specific path of block descendants, you need to repeatedly call `GET /v1/blocks/:id/children` on a block and its subsequent descendants, as you noticed. This allows us to keep the block response pagination simple.

@pascalporedda's approach is the recommended one for getting all of a block's descendants at this time. 

For future reference, we want the issues in this github repo to be specific to the SDK, not to the API as a whole. You can submit bugs and feature requests via Intercom by going to https://developers.notion.com/ and clicking "Help" in the footer.
