### ISSUE TITLE
block "Date or reminder" support?

### ISSUE THREAD

**Issue by tsukasa521** [makenotion/notion-sdk-js#246]

**Comment by jlpetracca** [comment]
UP

**Comment by cwang314** [comment]
Hi @tsukasa521, thanks for the API feature request; I've gone ahead and added this to our internal tracker. I'm closing this issue because we want the issues in this github repo to be SDK-specific. However, you can always submit bugs and feature requests for the API through Intercom by going to https://developers.notion.com/ and clicking "Help" in the footer.
