### ISSUE TITLE
api timeouts 

### ISSUE THREAD

**Issue by veritem** [makenotion/notion-sdk-js#254]
Report bugs here only for the Node JavaScript library.

Hey, I'm having a hard time working with notion SDK 

it's timeout every time a query something

![image](https://user-images.githubusercontent.com/53856673/151614385-7f1bedb6-7786-4ec4-b72c-46614b207fa2.png)

**Comment by cwang314** [comment]
Hi @veritem, do you mind sharing the requests you've been making?

**Comment by veritem** [comment]
Here you go 
![image](https://user-images.githubusercontent.com/53856673/152279802-c1a2d1ac-afb1-4e15-a99e-7b7c792f50b6.png)

**Comment by cwang314** [comment]
@veritem this looks like an API issue, not an SDK one - can you file this in Intercom? You can do this by going to https://developers.notion.com/ and clicking "Help" in the footer.

Closing this issue because we want issues in this github repo to be centered on the SDK specifically, not the API as a whole.
