### ISSUE TITLE
Rollup Array Properties Do Not Return the Right Type

### ISSUE THREAD

**Issue by chialuka** [makenotion/notion-sdk-js#282]
Report bugs here only for the Node JavaScript library.

If you're having problems using Notion's API, or have any other feedback about the API including feature requests for the JavaScript library, please email support at developers@makenotion.com.

**Describe the bug**
- The array property on `ArrayRollupValue` type does not return the type specified in `@notionhq/client/build/src/api-types`

**To Reproduce**
Node version: 16.x.x
Notion JS library version: 0.1.9

- Make a request to a database and try to access the `rollup` property on the returned page. The type of the property of the rollup array is different from the value in the `api-types` file

**Expected behavior**
After fetching a database from Notion, if I try to access the properties of a page:
```
  const value: PropertyValue = page.properties["property"];
  if (prop.type === "rollup" && prop.rollup.type === "array") {
        const val = prop.rollup.array[0];
        console.log(val.type)
  }

```
The type provided here should include `text` not just `rich_text` or the API should return `rich_text` and not `text`
**Screenshots**
Types from Notion
<img width="750" alt="Screenshot 2022-03-29 at 14 40 20" src="https://user-images.githubusercontent.com/42539315/160624809-93f4c272-8b5e-48f5-bd15-ce34d292abae.png">

Return Value from Notion API:
<img width="719" alt="Screenshot 2022-03-29 at 14 42 43" src="https://user-images.githubusercontent.com/42539315/160626811-1539259c-2b0c-4a4a-9c47-ca6b71ef266e.png">

**Additional context**

**Comment by rhart92** [comment]
By the look of the response from the Notion API, it looks like you have a mismatch of `SDK Client` version and `API` version. A while back we had a versioned change to move from `text` to `rich_text` which is why it isn't part of the Typescript types any more. You can find details about the change and the migration to the new property [here](https://developers.notion.com/changelog/unversioned-requests-no-longer-accepted). If you update your version to the latest, this issue should be resolved 🙏 )
