### ISSUE TITLE
database.list() returns empty array

### ISSUE THREAD

**Issue by Achder** [makenotion/notion-sdk-js#286]
Quote from another issue:

I'm also having this problem even though integration has a page with inline table and a table page shared with it.

![Screen Shot 2021-05-20 at 1 48 41 PM](https://user-images.githubusercontent.com/20071081/119025423-1da9a700-b972-11eb-87d8-66062e412b60.png)

and I'm running the supplied example SDK code from the reference:
```js
const { Client } = require('@notionhq/client');

const notion = new Client({ auth: process.env.NOTION_API_KEY });

(async () => {
  const response = await notion.databases.list();
  console.log(response);
})();
```

which returns

```bash

> node index.js

{ object: 'list', results: [], next_cursor: null, has_more: false }
```

_Originally posted by @iltimasd in https://github.com/makenotion/notion-sdk-js/issues/56#issuecomment-845338677_

We are having the same issue.
database.list() works most of the time. But sometimes it just returns an empty array with no error provided.

**Comment by rhart92** [comment]
@Achder, the list databases endpoint has been deprecated (see [docs](https://developers.notion.com/reference/get-databases)) because of this exact slightly confusing behavior. In the docs we have a callout that states:

> This endpoint will only return explicitly shared databases

In the screenshot above, the share menu shows that the bot has access `Based on Bot Training Grounds`, which means that the "Table Page" has not been explicitly shared with the bot and therefore won't be returned by `notion.databases.list`. To fetch this page, you'll want to use the search endpoint.
