### ISSUE TITLE
GIthub embed for private repos

### ISSUE THREAD

**Issue by y-nk** [makenotion/notion-sdk-js#293]
**Describe the bug**
Can't manage to embed code of private repos

**To Reproduce**
Node version: any
Notion JS library version: any

**Expected behavior**
1. Create a private repo, push some code
2. Get a permalink
3. Paste in Notion app/web

**Additional context**
Maybe it's necessary to connect Github <-> Notion with some permissions?

**Comment by rhart92** [comment]
@y-nk, seems like you are referencing the ability to embed link to a private github repository via the client. You can find some resources on how this works [here](https://www.notion.so/help/guides/notion-api-link-previews-feature) in our help documentation. Going to close since this isn't an issue with JS client.
