### ISSUE TITLE
Documentation clarification

### ISSUE THREAD

**Issue by melMass** [makenotion/notion-sdk-js#343]
Hi,

I'm re-working on my integration, but I'm a bit confused by the doc samples mentioning an `api` package:
<img width="474" alt="image" src="https://user-images.githubusercontent.com/7041726/189646909-6c6ba1d6-5258-4157-9750-2689ad59754e.png">

Is there a way to see the SDK wrapper code in the doc?

**Comment by melMass** [comment]
Oh I think this is an actual bug:

### First load
<img width="469" alt="image" src="https://user-images.githubusercontent.com/7041726/189647859-653c7636-de32-4900-9a38-6d71d144c857.png">

I just realised there is a tiny arrow with another menu, the `sdk` is not listed, `api` is
<img width="461" alt="image" src="https://user-images.githubusercontent.com/7041726/189648006-751696ed-5a1a-41f9-b697-36b3ad87a013.png">

Now switching back & forth to `Shell` than `Javascript`
SDK is now the default and `api` is not listed
<img width="489" alt="image" src="https://user-images.githubusercontent.com/7041726/189648153-decf6396-5fb3-4c2e-ae49-3eec3fd45854.png">
<img width="471" alt="image" src="https://user-images.githubusercontent.com/7041726/189648263-a9aa3b5d-f902-4d51-95cb-f416bdf1e1e1.png">

**Comment by lao9** [comment]
@melMass - would you mind explaining a bit more what the issue is here? 

What are you expecting to happen and what is actually happening?

Is there a specific link to an example you could provide?

I don't see anything amiss on the queryDatabase page:

Shell | JavaScript
--- | ---
<img width="1049" alt="image" src="https://user-images.githubusercontent.com/4068853/194390602-b32054d3-8931-4905-b44c-b9cb877341ce.png"> | <img width="1058" alt="image" src="https://user-images.githubusercontent.com/4068853/194390684-f56d3941-ad2c-4060-bff2-5a0e44fa20f0.png">

**Comment by abdualhramzan** [comment]
مرحبا  انا منشئ محتوى في التيك توك وتوقف ظهور محتوى حسابي فجأة في الظهور في ال foryou  هناك خطأ في الرابط الخاص بي لأعرف ماهو والحل  وانا لااعرف  في البرمجة شيء ارجو منكم المساعدة وشكرا 
https://www.tiktok.com/@abdualhramzan?_t=8X3pirLPtBJ&_r=1
هذا هو عنوان url
