### ISSUE TITLE
page update is not working 

### ISSUE THREAD

**Issue by nabildroid** [makenotion/notion-sdk-js#37]
both the SDK, API returns 404 error when i request page properties update, but everything works fine when requesting page information

```typescript

const PAGEID = "5044618ceecc499f891f270e3bb66b26";
workspace.pages
  .retrieve({
    page_id: PAGEID,
  })
  .then((page) => {
    const titleProperty = (page.properties["title"] as TitlePropertyValue)
      .title;
    const title = titleProperty[0].plain_text;
    console.log("page ["+title+"], id#", page.id);

    workspace.request({
      path: `pages/${PAGEID}`,
      method: "patch",
      body: {
        properties: {
          title: createTitle(`${title}1`),
        },
      },
    })

  });

function createTitle(content: string): TitlePropertyValue {
  return {
    type: "title",
    id: "8868",
    title: [
      {
        type: "text",
        plain_text: content,
        text: {
          content,
        },
        annotations: {
          bold: false,
          italic: false,
          strikethrough: false,
          underline: false,
          code: false,
          color: "default",
        },
      },
    ],
  };
}
```

ps: the (private )page has the integration permission

**Comment by aoberoi** [comment]
Hi @nabildroid, could you try removing the `id: "8868"` part of the object returned from `createTitle()`? When you make the request to update the page properties, and the top level key for the property is `title` - that is the property's ID. every page has one property of type `title` whose ID is also `title`.

You can also omit the `plain_text` property, and the `annotations` property since you're not setting it to anything other than what the default would be.

Let me know if that works. I will try to figure out what this is going you a 404, because from my understanding this should be a 400 - validation_error.

**Comment by aoberoi** [comment]
seems pretty clear this isn't an SDK issue (since you said it's happening just directly using the API). im still happy to keep this open to discuss, but i'm moving it out of issues and into discussions.
