### ISSUE TITLE
Next.JS Docker container build fails without ENV variables (Incremental Static Regeneration)

### ISSUE THREAD

**Issue by ochoadan** [makenotion/notion-sdk-js#370]
Report bugs here only for the Node JavaScript library.

If you're having problems using Notion's API, or have any other feedback about the API including feature requests for the JavaScript library, please email support at developers@makenotion.com.

**Describe the bug**
A lack of environment variables leads to failure on production build on (docker) containers.

**To Reproduce**
Node version: [18.12.1]
Notion JS library version: 2.2.2

1. Create a next.js project with notion client.
2. Create notion database
3. use [Incremental Static Regeneration](https://nextjs.org/docs/basic-features/data-fetching/incremental-static-regeneration) to fetch data through notion
4. Build project through Docker Image

**Expected behavior**
It's expected for these pages to not be built with through [Incremental Static Regeneration](https://nextjs.org/docs/basic-features/data-fetching/incremental-static-regeneration) on Next.JS without producing an error and be generated later through if environment variables are found when build is deployed.

This forces me to import the environment variables when I build my application, risking security.

**Screenshots**
NPM run build with env variables
![Capture](https://user-images.githubusercontent.com/42155753/205745607-c747714d-e6c4-413e-954f-75c8057eafd1.PNG)
Container (Docker) Build without environment variables…
![Capture](https://user-images.githubusercontent.com/42155753/205746034-8d7b12b5-98a8-40b0-9216-3cc51b28bb66.PNG)

**Comment by wcauchois** [comment]
Hi! This doesn't look like an issue with the Notion SDK, more maybe something about how you're using it with Next? I'm really not familiar with this static regeneration that you're talking about, but the SDK _will_ need a secret in order to access Notion, so you'll need to thread that through somehow. Perhaps you could file an issue in the Next.JS repo asking for best practices around providing secrets for this regeneration.
