### ISSUE TITLE
Use `collectPaginatedAPI` with `notion.pages.properties.retrieve`

### ISSUE THREAD

**Issue by harryzcy** [makenotion/notion-sdk-js#372]
**Describe the bug**
It's unable to use `collectPaginatedAPI` with `notion.pages.properties.retrieve`, even though the endpoint "will return a paginated list of property item objects" for type `title`, `rich_text`, `relation`, and `people`.

**To Reproduce**
Node version: v18.12.1
Notion JS library version: v2.2.2

```
await collectPaginatedAPI(notion.pages.properties.retrieve, {
      page_id,,
      property_id,
    })
  }
```

**Expected behavior**
It should be supported

**Comment by wcauchois** [comment]
Hi! collectPaginatedAPI will unfortunately not be able to work with properties.retrieve, because it expects a certain uniform list response type and the property retrieval endpoint may return either a full property _or_ a list.

In order to fully retrieve page properties, you should use something like the `getPropertyValue` function [from our example](https://github.com/makenotion/notion-sdk-js/blob/97c98419e7106a4865cdbb6230ceeebf40ae39e3/examples/database-email-update/index.js#L168). We'll consider incorporating this helper into a future version of the SDK.
